name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install PostgreSQL
        run: sudo apt-get install postgresql postgresql-contrib

      - name: Start PostgreSQL service
        run: sudo service postgresql start

      - name: Set up database
        run: |
          sudo -u postgres psql -c "CREATE USER admin WITH PASSWORD 'admin';"
          sudo -u postgres psql -c "CREATE DATABASE movie_library OWNER admin;"

      - name: Test
        run: npm test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
